import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className="bg-[#141414] x-scroll flex items-center justify-center mx-2"
    >
      <body className="w-full max-w-6xl box-border">{children}</body>
    </html>
  );
}
